# Generated by Django 4.2.7 on 2026-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp_number", models.CharField(max_length=20)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Vlog Edit", "Vlog Edit"),
                            ("Documentary Edit", "Documentary Edit"),
                            ("Reel Edit", "Reel Edit"),
                            ("AI Edit", "AI Edit"),
                            ("Custom Edit", "Custom Edit"),
                            ("Wedding Edit", "Wedding Edit"),
                            ("Professional Shoot", "Professional Shoot"),
                        ],
                        max_length=50,
                    ),
                ),
                ("project_title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "video_duration",
                    models.CharField(
                        choices=[
                            ("Under 1 minute", "Under 1 minute"),
                            ("1-5 minutes", "1-5 minutes"),
                            ("5-15 minutes", "5-15 minutes"),
                            ("15-30 minutes", "15-30 minutes"),
                            ("30+ minutes", "30+ minutes"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("YouTube Video", "YouTube Video"),
                            ("Instagram Reel", "Instagram Reel"),
                            ("TikTok", "TikTok"),
                            ("Documentary", "Documentary"),
                            ("Wedding", "Wedding"),
                            ("Corporate", "Corporate"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        choices=[
                            ("₹0-500", "₹0-500"),
                            ("₹500-1000", "₹500-1000"),
                            ("₹1000-2500", "₹1000-2500"),
                            ("₹2500-5000", "₹2500-5000"),
                            ("₹5000+", "₹5000+"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("Urgent (24-48 hours)", "Urgent (24-48 hours)"),
                            ("ASAP (3-7 days)", "ASAP (3-7 days)"),
                            ("1-2 weeks", "1-2 weeks"),
                            ("2-4 weeks", "2-4 weeks"),
                            ("Flexible", "Flexible"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reference_video_link", models.URLField()),
                ("portfolio_link", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service Booking",
                "verbose_name_plural": "Service Bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="bookings_se_created_a3163a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="bookings_se_status_bc864a_idx"
                    ),
                    models.Index(
                        fields=["service_type"], name="bookings_se_service_5b4463_idx"
                    ),
                ],
            },
        ),
    ]
