# Generated by Django 4.2.7 on 2026-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebooking",
            name="portfolio_link",
        ),
        migrations.RemoveField(
            model_name="servicebooking",
            name="video_duration",
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="location",
            field=models.CharField(
                choices=[
                    ("Mumbai", "Mumbai"),
                    ("Delhi", "Delhi"),
                    ("Bangalore", "Bangalore"),
                    ("Hyderabad", "Hyderabad"),
                    ("Chennai", "Chennai"),
                    ("Kolkata", "Kolkata"),
                    ("Pune", "Pune"),
                    ("Ahmedabad", "Ahmedabad"),
                    ("Jaipur", "Jaipur"),
                    ("Lucknow", "Lucknow"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
    ]
