# Generated by Django 4.2.7 on 2026-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_servicebooking_portfolio_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShootBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp_number", models.CharField(max_length=20)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("sehore", "Sehore"),
                            ("bhopal", "Bhopal"),
                            ("Indore", "Indore"),
                            ("Gwalior", "Gwalior"),
                            ("Ujjain", "Ujjain"),
                            ("Jabalpur", "Jabalpur"),
                            ("Mumbai", "Mumbai"),
                            ("Delhi", "Delhi"),
                            ("Bangalore", "Bangalore"),
                            ("Hyderabad", "Hyderabad"),
                            ("Chennai", "Chennai"),
                            ("Kolkata", "Kolkata"),
                            ("Pune", "Pune"),
                            ("Ahmedabad", "Ahmedabad"),
                            ("Jaipur", "Jaipur"),
                            ("Lucknow", "Lucknow"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "shoot_type",
                    models.CharField(
                        choices=[
                            ("Wedding Shoot", "Wedding Shoot"),
                            (
                                "Insta & YouTube Video Shoot",
                                "Insta & YouTube Video Shoot",
                            ),
                            ("Commercial Shoot", "Commercial Shoot"),
                            ("Corporate Event Shoot", "Corporate Event Shoot"),
                            ("Marketing Shoot", "Marketing Shoot"),
                            ("Religious Shoot", "Religious Shoot"),
                            ("Political Shoot", "Political Shoot"),
                            ("Cinematic Shoot", "Cinematic Shoot"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "event_details",
                    models.TextField(
                        help_text="Tell us more about your shoot - location, date, special requirements..."
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        choices=[
                            ("₹0-500", "₹0-500"),
                            ("₹500-1000", "₹500-1000"),
                            ("₹1000-2500", "₹1000-2500"),
                            ("₹2500-5000", "₹2500-5000"),
                            ("₹5000+", "₹5000+"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("Urgent (24-48 hours)", "Urgent (24-48 hours)"),
                            ("ASAP (3-7 days)", "ASAP (3-7 days)"),
                            ("1-2 weeks", "1-2 weeks"),
                            ("2-4 weeks", "2-4 weeks"),
                            ("Flexible", "Flexible"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reference_video_link", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Shoot Booking",
                "verbose_name_plural": "Shoot Bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="bookings_sh_created_c8b7e6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="bookings_sh_status_8ec077_idx"
                    ),
                    models.Index(
                        fields=["shoot_type"], name="bookings_sh_shoot_t_655ca7_idx"
                    ),
                ],
            },
        ),
    ]
