# Generated by Django 6.0.2 on 2026-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_shootbooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="InnerCircleApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("gmail", models.EmailField(max_length=254)),
                (
                    "achievement",
                    models.TextField(
                        help_text="Tell us about your greatest achievement"
                    ),
                ),
                (
                    "top_skill",
                    models.CharField(
                        help_text="e.g., Digital Marketing, Video Editing, Business Strategy",
                        max_length=255,
                    ),
                ),
                ("portfolio_link", models.URLField()),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Inner Circle Application",
                "verbose_name_plural": "Inner Circle Applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="bookings_in_created_346890_idx"
                    ),
                    models.Index(
                        fields=["status"], name="bookings_in_status_e3c67c_idx"
                    ),
                    models.Index(fields=["state"], name="bookings_in_state_fabbe8_idx"),
                ],
            },
        ),
    ]
