# Generated by Django 6.0.2 on 2026-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_innercircleapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalSolutionBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Website Design", "Website Design"),
                            ("Automation", "Automation"),
                            ("AI Bot", "AI Bot"),
                            ("Insta Auto Reply", "Insta Auto Reply"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Technical Solution Booking",
                "verbose_name_plural": "Technical Solution Bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="bookings_te_created_955fe6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="bookings_te_status_aecea5_idx"
                    ),
                ],
            },
        ),
    ]
