# Generated by Django 6.0.2 on 2026-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_technicalsolutionbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
