# Generated by Django 6.0.2 on 2026-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_servicebooking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='content_type',
            field=models.CharField(blank=True, choices=[('YouTube Video', 'YouTube Video'), ('Instagram Reel', 'Instagram Reel'), ('TikTok', 'TikTok'), ('Documentary', 'Documentary'), ('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='timeline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shootbooking',
            name='budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shootbooking',
            name='event_details',
            field=models.TextField(blank=True, default='', help_text='Tell us more about your shoot - location, date, special requirements...'),
        ),
        migrations.AlterField(
            model_name='shootbooking',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shootbooking',
            name='timeline',
            field=models.CharField(max_length=100),
        ),
    ]
